# Form implementation generated from reading ui file 'main_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(943, 527)
        Form.setMinimumSize(QtCore.QSize(940, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.On,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Disabled,
            QtGui.QIcon.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Disabled,
            QtGui.QIcon.On,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Active,
            QtGui.QIcon.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Active,
            QtGui.QIcon.On,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Selected,
            QtGui.QIcon.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                ":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/RoniHernandez99_IoT_domotica_128px.ico"
            ),
            QtGui.QIcon.Selected,
            QtGui.QIcon.On,
        )
        Form.setWindowIcon(icon)
        Form.setStyleSheet(
            "#Form{    \n"
            "border:1px solid white;\n"
            "background-color: #193b58;\n"
            "padding:0;\n"
            "}\n"
            "\n"
            ""
        )
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Mexico))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_alarmasNotas = QtWidgets.QWidget(Form)
        self.widget_alarmasNotas.setMinimumSize(QtCore.QSize(410, 410))
        self.widget_alarmasNotas.setStyleSheet(
            "#widget_alarmasNotas{\n"
            "margin:0px;\n"
            "background-color:#d8d8d8;\n"
            "padding: 50px 50px 50px 50px;\n"
            "padding: 0;\n"
            "}"
        )
        self.widget_alarmasNotas.setObjectName("widget_alarmasNotas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_alarmasNotas)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(26, 26, 26, 26)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_info = QtWidgets.QPushButton(self.widget_alarmasNotas)
        self.btn_info.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_info.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_info.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_info.setBaseSize(QtCore.QSize(25, 25))
        self.btn_info.setStyleSheet(
            "QPushButton {\n"
            "border-image:url(:/iconos_estandar/multimedia/imagenes/estandar/info_off.png);\n"
            " }\n"
            "\n"
            "QPushButton:hover {\n"
            "border-image:url(:/iconos_estandar/multimedia/imagenes/estandar/info_on.png);;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "border-image:url(:/iconos_estandar/multimedia/imagenes/estandar/info_off.png);\n"
            "}"
        )
        self.btn_info.setText("")
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout_15.addWidget(self.btn_info)
        self.bel_estacion_clic = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.bel_estacion_clic.setMinimumSize(QtCore.QSize(63, 63))
        self.bel_estacion_clic.setMaximumSize(QtCore.QSize(150, 150))
        self.bel_estacion_clic.setBaseSize(QtCore.QSize(63, 63))
        self.bel_estacion_clic.setStyleSheet(
            "image: url(:/estaciones_metro/multimedia/imagenes/estaciones_metro/todas/san lazaro.png);"
        )
        self.bel_estacion_clic.setText("")
        self.bel_estacion_clic.setObjectName("bel_estacion_clic")
        self.horizontalLayout_15.addWidget(self.bel_estacion_clic)
        self.label_19 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rb_con_sonido = QtWidgets.QRadioButton(self.widget_alarmasNotas)
        self.rb_con_sonido.setMinimumSize(QtCore.QSize(20, 20))
        self.rb_con_sonido.setMaximumSize(QtCore.QSize(30, 30))
        self.rb_con_sonido.setSizeIncrement(QtCore.QSize(0, 0))
        self.rb_con_sonido.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_con_sonido.setFont(font)
        self.rb_con_sonido.setStyleSheet(
            "QRadioButton {\n"
            "\n"
            "}\n"
            "\n"
            "QRadioButton::indicator {\n"
            "    width:                  15px;\n"
            "    height:                 15px;\n"
            "    border-radius:          9px;\n"
            "    border:                 2px solid black;\n"
            "}\n"
            "\n"
            "QRadioButton::indicator:checked {\n"
            "    background-color:        #193b58;\n"
            "    border:                 2px solid black;\n"
            "}\n"
            "\n"
            "QRadioButton::indicator:unchecked {\n"
            "    background-color:       #d8d8d8;\n"
            "    border:                  2px solid black;\n"
            "}\n"
            ""
        )
        self.rb_con_sonido.setText("")
        self.rb_con_sonido.setObjectName("rb_con_sonido")
        self.verticalLayout_7.addWidget(self.rb_con_sonido, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_7.setMinimumSize(QtCore.QSize(100, 20))
        self.label_7.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("LucidaGrande")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(
            "  font-family: LucidaGrande;\n"
            "  font-size: 16px;\n"
            "  font-weight: normal;\n"
            "  font-stretch: normal;\n"
            "  font-style: normal;\n"
            "  line-height: normal;\n"
            "  letter-spacing: normal;\n"
            "  color: black;\n"
            "  /*border: 1px solid  #193b58; */\n"
            "background-color: #d8d8d8;\n"
            " /*font-weight: bold;*/"
        )
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rb_sin_sonido = QtWidgets.QRadioButton(self.widget_alarmasNotas)
        self.rb_sin_sonido.setMinimumSize(QtCore.QSize(20, 20))
        self.rb_sin_sonido.setMaximumSize(QtCore.QSize(30, 30))
        self.rb_sin_sonido.setSizeIncrement(QtCore.QSize(0, 0))
        self.rb_sin_sonido.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_sin_sonido.setFont(font)
        self.rb_sin_sonido.setStyleSheet(
            "QRadioButton {\n"
            "\n"
            "}\n"
            "\n"
            "QRadioButton::indicator {\n"
            "    width:                  15px;\n"
            "    height:                 15px;\n"
            "    border-radius:          9px;\n"
            "    border:                 2px solid black;\n"
            "}\n"
            "\n"
            "QRadioButton::indicator:checked {\n"
            "    background-color:        #193b58;\n"
            "    border:                 2px solid black;\n"
            "}\n"
            "\n"
            "QRadioButton::indicator:unchecked {\n"
            "    background-color:       #d8d8d8;\n"
            "    border:                  2px solid black;\n"
            "}"
        )
        self.rb_sin_sonido.setText("")
        self.rb_sin_sonido.setChecked(True)
        self.rb_sin_sonido.setObjectName("rb_sin_sonido")
        self.verticalLayout_9.addWidget(self.rb_sin_sonido, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_11.setMinimumSize(QtCore.QSize(100, 20))
        self.label_11.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("LucidaGrande")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(
            "  font-family: LucidaGrande;\n"
            "  font-size: 16px;\n"
            "  font-weight: normal;\n"
            "  font-stretch: normal;\n"
            "  font-style: normal;\n"
            "  line-height: normal;\n"
            "  letter-spacing: normal;\n"
            "  color: black;\n"
            "  /*border: 1px solid  #193b58; */\n"
            "background-color: #d8d8d8;\n"
            " /*font-weight: bold;*/"
        )
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.label_3 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_3.setMinimumSize(QtCore.QSize(181, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.cmb__box_ruta = QtWidgets.QComboBox(self.widget_alarmasNotas)
        self.cmb__box_ruta.setObjectName("cmb__box_ruta")
        self.horizontalLayout_5.addWidget(self.cmb__box_ruta)
        self.label_10 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.bel_no_estaciones = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.bel_no_estaciones.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_no_estaciones.setObjectName("bel_no_estaciones")
        self.horizontalLayout_5.addWidget(self.bel_no_estaciones)
        self.label_13 = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.bel_dst_ruta = QtWidgets.QLabel(self.widget_alarmasNotas)
        self.bel_dst_ruta.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_dst_ruta.setObjectName("bel_dst_ruta")
        self.horizontalLayout_5.addWidget(self.bel_dst_ruta)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.widget_alarmasNotas)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.stack_panel_metro = QtWidgets.QStackedWidget(self.widget_alarmasNotas)
        self.stack_panel_metro.setMinimumSize(QtCore.QSize(380, 160))
        self.stack_panel_metro.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stack_panel_metro.setBaseSize(QtCore.QSize(380, 160))
        self.stack_panel_metro.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stack_panel_metro.setToolTipDuration(0)
        self.stack_panel_metro.setStyleSheet(
            "QStackedWidget#stack_notas{\n"
            "padding:0px;\n"
            "background-color: #d8d8d8;\n"
            "/*border-radius: 20%;*/\n"
            "margin-top: 5px;\n"
            "margin: 0px;\n"
            "}\n"
            "\n"
            "\n"
            "QWidget{\n"
            "background-color: rgb(255, 255, 255);\n"
            "margin:0px;\n"
            "padding:0px;\n"
            "background-color: #d8d8d8;\n"
            "margin-top: 5px;\n"
            "}\n"
            "\n"
            "\n"
            "*{\n"
            "background-color: #d8d8d8;\n"
            "/*border-radius: 20%*/;\n"
            "margin: 0px;\n"
            "margin-top: 5px;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            ""
        )
        self.stack_panel_metro.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stack_panel_metro.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stack_panel_metro.setObjectName("stack_panel_metro")
        self.verticalLayout_2.addWidget(self.stack_panel_metro)
        self.horizontalLayout_3.addWidget(self.widget_alarmasNotas)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(130, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(100, 160))
        self.widget_3.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.widget_3.setBaseSize(QtCore.QSize(100, 160))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bel_estacion_origen = QtWidgets.QLabel(self.widget_3)
        self.bel_estacion_origen.setMinimumSize(QtCore.QSize(70, 60))
        self.bel_estacion_origen.setMaximumSize(QtCore.QSize(160, 150))
        self.bel_estacion_origen.setSizeIncrement(QtCore.QSize(0, 0))
        self.bel_estacion_origen.setBaseSize(QtCore.QSize(60, 50))
        self.bel_estacion_origen.setStyleSheet(
            "image: url(:/estaciones_metro/multimedia/imagenes/estaciones_metro/todas/observatorio.png);"
        )
        self.bel_estacion_origen.setText("")
        self.bel_estacion_origen.setObjectName("bel_estacion_origen")
        self.verticalLayout_3.addWidget(self.bel_estacion_origen)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmb_box_origen = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cmb_box_origen.sizePolicy().hasHeightForWidth()
        )
        self.cmb_box_origen.setSizePolicy(sizePolicy)
        self.cmb_box_origen.setObjectName("cmb_box_origen")
        self.horizontalLayout_2.addWidget(self.cmb_box_origen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 110))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.btn_buscar = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_buscar.sizePolicy().hasHeightForWidth())
        self.btn_buscar.setSizePolicy(sizePolicy)
        self.btn_buscar.setObjectName("btn_buscar")
        self.verticalLayout_4.addWidget(self.btn_buscar)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(100, 160))
        self.widget_5.setSizeIncrement(QtCore.QSize(100, 160))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.bel_estacion_destino = QtWidgets.QLabel(self.widget_5)
        self.bel_estacion_destino.setMinimumSize(QtCore.QSize(63, 63))
        self.bel_estacion_destino.setMaximumSize(QtCore.QSize(150, 150))
        self.bel_estacion_destino.setBaseSize(QtCore.QSize(63, 63))
        self.bel_estacion_destino.setStyleSheet(
            "image: url(:/estaciones_metro/multimedia/imagenes/estaciones_metro/todas/san lazaro.png);"
        )
        self.bel_estacion_destino.setText("")
        self.bel_estacion_destino.setObjectName("bel_estacion_destino")
        self.verticalLayout_8.addWidget(self.bel_estacion_destino)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmb_box_destino = QtWidgets.QComboBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cmb_box_destino.sizePolicy().hasHeightForWidth()
        )
        self.cmb_box_destino.setSizePolicy(sizePolicy)
        self.cmb_box_destino.setObjectName("cmb_box_destino")
        self.horizontalLayout.addWidget(self.cmb_box_destino)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.horizontalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.stack_panel_metro.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "RoniHernandez99/IoT_domotica"))
        self.label_7.setText(_translate("Form", "Con sonido"))
        self.label_11.setText(_translate("Form", "Sin sonido"))
        self.label_3.setText(_translate("Form", "Red del metro"))
        self.label_9.setText(_translate("Form", "Ruta a seguir:"))
        self.label_10.setText(_translate("Form", "No. estaciones:"))
        self.bel_no_estaciones.setText(_translate("Form", "10"))
        self.label_13.setText(_translate("Form", "Distancia en\n" "metros: "))
        self.bel_dst_ruta.setText(_translate("Form", "1520"))
        self.btn_buscar.setText(_translate("Form", "OBTENER RUTA"))


import images_rc
